use crate::domain::DomainId;
use crate::pane::*;
use crate::{Mux, MuxNotification, WindowId};
use bintree::PathBranch;
use config::configuration;
use config::keyassignment::PaneDirection;
use parking_lot::Mutex;
use rangeset::intersects_range;
use std::collections::HashMap;
use std::convert::TryInto;
use std::sync::Arc;
use wezterm_term::TerminalSize;

include!("tab/types.rs");
include!("tab/tree.rs");
include!("tab/tab_impl.rs");
include!("tab/inner_iter.rs");
include!("tab/inner_resize.rs");
include!("tab/inner_focus.rs");
include!("tab/inner_split.rs");
include!("tab/tail.rs");
