def build_toc(Page, Gen, GenColorScheme):
    return [
        Page(
            "WezTerm",
            "index.md",
            children=[
                Page("Features", "features.md"),
                Page("Scrollback", "scrollback.md"),
                Page("Quick Select Mode", "quickselect.md"),
                Page("Copy Mode", "copymode.md"),
                Page("Hyperlinks", "hyperlinks.md"),
                Page("Shell Integration", "shell-integration.md"),
                Page("iTerm Image Protocol", "imgcat.md"),
                Page("SSH", "ssh.md"),
                Page("Serial Ports & Arduino", "serial.md"),
                Page("Multiplexing", "multiplexing.md"),
            ],
        ),
        Page(
            "Download",
            "installation.md",
            children=[
                Page("Windows", "install/windows.md"),
                Page("macOS", "install/macos.md"),
                Page("Linux", "install/linux.md"),
                Page("FreeBSD", "install/freebsd.md"),
                Page("NetBSD", "install/netbsd.md"),
                Page("Build from source", "install/source.md"),
            ],
        ),
        Page(
            "Configuration",
            "config/files.md",
            children=[
                Page("Colors & Appearance", "config/appearance.md"),
                Page("Launching Programs", "config/launch.md"),
                Page("Fonts", "config/fonts.md"),
                Page("Font Shaping", "config/font-shaping.md"),
                Page("Keyboard Concepts", "config/keyboard-concepts.md"),
                Page("Key Binding", "config/keys.md"),
                Page("Key Tables", "config/key-tables.md"),
                Page("Default Key Assignments", "config/default-keys.md"),
                Page("Keyboard Encoding", "config/key-encoding.md"),
                Page("Mouse Binding", "config/mouse.md"),
                Page("Plugins", "config/plugins.md"),
                GenColorScheme("Color Schemes", "colorschemes"),
                Gen("Recipes", "recipes", extract_title=True),
            ],
        ),
        Page(
            "Full Config & Lua Reference",
            "config/lua/general.md",
            children=[
                Gen(
                    "Config Options",
                    "config/lua/config",
                ),
                Gen(
                    "module: wezterm",
                    "config/lua/wezterm",
                ),
                Gen(
                    "module: wezterm.color",
                    "config/lua/wezterm.color",
                ),
                Gen(
                    "module: wezterm.gui",
                    "config/lua/wezterm.gui",
                ),
                Gen(
                    "module: wezterm.mux",
                    "config/lua/wezterm.mux",
                ),
                Gen(
                    "module: wezterm.plugin",
                    "config/lua/wezterm.plugin",
                ),
                Gen(
                    "module: wezterm.procinfo",
                    "config/lua/wezterm.procinfo",
                ),
                Gen(
                    "module: wezterm.serde",
                    "config/lua/wezterm.serde",
                ),
                Gen(
                    "module: wezterm.time",
                    "config/lua/wezterm.time",
                ),
                Gen(
                    "module: wezterm.url",
                    "config/lua/wezterm.url",
                ),
                Gen(
                    "enum: KeyAssignment",
                    "config/lua/keyassignment",
                ),
                Gen(
                    "enum: CopyModeAssignment",
                    "config/lua/keyassignment/CopyMode",
                ),
                Gen("object: Color", "config/lua/color"),
                Page("object: ExecDomain", "config/lua/ExecDomain.md"),
                Page("object: LocalProcessInfo", "config/lua/LocalProcessInfo.md"),
                Gen("object: MuxDomain", "config/lua/MuxDomain"),
                Gen("object: MuxWindow", "config/lua/mux-window"),
                Gen("object: MuxTab", "config/lua/MuxTab"),
                Page("object: PaneInformation", "config/lua/PaneInformation.md"),
                Page("object: TabInformation", "config/lua/TabInformation.md"),
                Page("object: SshDomain", "config/lua/SshDomain.md"),
                Page("object: SpawnCommand", "config/lua/SpawnCommand.md"),
                Gen("object: Time", "config/lua/wezterm.time/Time"),
                Page("object: TlsDomainClient", "config/lua/TlsDomainClient.md"),
                Page("object: TlsDomainServer", "config/lua/TlsDomainServer.md"),
                Gen(
                    "object: Pane",
                    "config/lua/pane",
                ),
                Gen(
                    "object: Window",
                    "config/lua/window",
                ),
                Page("object: WslDomain", "config/lua/WslDomain.md"),
                Gen(
                    "events: Gui",
                    "config/lua/gui-events",
                ),
                Gen(
                    "events: Multiplexer",
                    "config/lua/mux-events",
                ),
                Gen(
                    "events: Window",
                    "config/lua/window-events",
                ),
            ],
        ),
        Page(
            "CLI Reference",
            "cli/general.md",
            children=[
                Gen("wezterm cli", "cli/cli"),
                Page("wezterm connect", "cli/connect.md"),
                Page("wezterm imgcat", "cli/imgcat.md"),
                Page("wezterm ls-fonts", "cli/ls-fonts.md"),
                Page("wezterm record", "cli/record.md"),
                Page("wezterm replay", "cli/replay.md"),
                Page("wezterm serial", "cli/serial.md"),
                Page("wezterm set-working-directory", "cli/set-working-directory.md"),
                Page("wezterm show-keys", "cli/show-keys.md"),
                Page("wezterm ssh", "cli/ssh.md"),
                Page("wezterm start", "cli/start.md"),
            ],
        ),
        Page(
            "Reference",
            None,
            children=[
                Page("Escape Sequences", "escape-sequences.md"),
                Page("What is a Terminal?", "what-is-a-terminal.md"),
            ],
        ),
        Page(
            "Get Help",
            None,
            children=[
                Page("Troubleshooting", "troubleshooting.md"),
                Page("F.A.Q.", "faq.md"),
                Page("Getting Help", "help.md"),
                Page("Contributing", "contributing.md"),
            ],
        ),
        Page("Change Log", "changelog.md"),
        Page("Sponsor", "sponsor.md"),
    ]
